FROM golang:1.4.2

RUN mkdir -p /go/src/app
WORKDIR /go/src/app

COPY go-wrapper /usr/local/bin/
# this will ideally be built by the ONBUILD below ;)
CMD ["go-wrapper", "run"]

COPY . /go/src/app
RUN go-wrapper download
RUN go-wrapper installstatic
